# Generated by Django 5.0.1 on 2024-02-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_enterproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
